Settings:
  Prefix: '§7[§3Server§7]§5 > §r'
  NoPermission: '§cDu Hast nicht Die Berichtigung um Den Befehl Auszuführen'
Spawn:
  ToSpawn: '&2Du bist jetzt am Spawn!'
  NoSpawnpoint: '&4Der Spawn wurde noch nicht gesetzt!'
  SpeakDeveloper: '&4Bitte wende dich an einen Developer!'
  MoveSpawn: '&2Der Spawn wurde verschopen!'
  SetSpawn: '&2Der Spawn wurde gesetzt!'
  SpawnCMD: '&4Benutze /spawn'
Vanish:
  Show: 'Du Bist nun Sichtbar Jeder kann dich Sehen!'
  Hide: 'Du Bist nun Unsichtbar keiner kann dich Sehen'
Sun:
  Sunny: 'Es ist nun Sonnig!'
Fly:
  CanFly: '&aDu kannst nun fliegen.'
  CantFly: '&aDu kannst nun §6nicht mehr fliegen.'
  CanOtherFly: '&6%player% &akann nun Fliegen.'
  CantOtherFly: '&6%player% &akann nun nicht mehr Fliegen.'
  UnknownPlayer: '&cSpieler &6%Player% &cnicht gefunden!'
  FlyCMD: '&cWrong Usage: /fly oder /fly <Name>'
Day:
  Day: '&aEs ist nun &6Tag!'