name: CustomServerUtilv2
version: 1.0.3
main: net.snapecraft.CustomServerUtilv2.main.CustomServerUtilv2
author: SnapecraftDevTeam 
commands:
  c:
    description: Creative mode
  s:
   description: Survival mode
  sp:
    description: Spectator mode
  day:
    description: Time to Day
  sun:
    description: Sunny weather
  tpa:
    description: Send Teleportation request
  tpahere:
    description: Send Teleportation request to Player
  tpaccept:
    description: Accept´s Teleportation request
  tpdecline:
    description: Decline´s Teleportation request
  fly:
    description: Fly like a bird
  vanish:
    description: Invisible
    aliases: [v]
  homes:
    description: See all your Homes
  sethome:
    description: Set a Home
  delhome:
    description: Delete a Home
  home:
    description: Teleportation to a Home
  setwarp:
    description: Set a Warp
  warps:
    description: See all warps
  warp:
    description: Teleportation to a warp
                
       
            